# Generated by Django 5.1.11 on 2026-02-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.PositiveBigIntegerField()),
                ('password', models.CharField(max_length=128)),
                ('class_name', models.CharField(choices=[('S1', 'Senior 1'), ('S2', 'Senior 2'), ('S3', 'Senior 3'), ('S4', 'Senior 4'), ('S5', 'Senior 5'), ('S6', 'Senior 6')], max_length=10)),
                ('subject_name', models.CharField(choices=[('ENG', 'English'), ('MTC', 'Math'), ('SCI', 'Science'), ('SST', 'Social Studies'), ('RE', 'Religious Education')], max_length=10)),
            ],
        ),
    ]
