# Generated by Django 6.0.3 on 2026-04-11 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherportal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4)),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='subject_name',
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject_names',
            field=models.ManyToManyField(to='teacherportal.subjectname'),
        ),
    ]
