# Generated by Django 5.1.11 on 2026-02-21 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentportal', '0002_student_term'),
        ('studentportal', '0005_remove_student_subjects'),
    ]

    operations = [
    ]
