# Generated by Django 5.1.11 on 2026-02-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentportal', '0006_merge_0002_student_term_0005_remove_student_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='term',
        ),
        migrations.AddField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='student_pics/'),
        ),
    ]
